version: "3"
services:

  ##
  ## Start services required for Lowcoder (MongoDB and Redis)
  ##
  mongodb:
    image: "mongo:4.4"
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: lowcoder
      MONGO_INITDB_ROOT_USERNAME: lowcoder
      MONGO_INITDB_ROOT_PASSWORD: secret123
    # Uncomment to save database data into local 'mongodata' folder
    # volumes:
    #   - ./mogodata:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis


  ##
  ## Start Lowcoder backend services (api-service and node-service)
  ##
  lowcoder-api-service:
    image: lowcoderorg/lowcoder-ce-api-service:latest
    container_name: lowcoder-api-service
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "8080:8080"
    environment:
      PUID: "9001"
      PGID: "9001"
      MONGODB_URL: "mongodb://lowcoder:secret123@mongodb/lowcoder?authSource=admin"
      REDIS_URL: "redis://redis:6379"
      LOWCODER_NODE_SERVICE_URL: "http://lowcoder-node-service:6060"
      LOWCODER_MAX_QUERY_TIMEOUT: 120
      ENABLE_USER_SIGN_UP: "true"
      ENCRYPTION_PASSWORD: "lowcoder.org"
      ENCRYPTION_SALT: "lowcoder.org"
      CORS_ALLOWED_DOMAINS: "*"
      DEFAULT_ORGS_PER_USER: 100
      DEFAULT_ORG_MEMBER_COUNT: 1000
      DEFAULT_ORG_GROUP_COUNT: 100
      DEFAULT_ORG_APP_COUNT: 1000
      DEFAULT_DEVELOPER_COUNT: 50
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  lowcoder-node-service:
    image: lowcoderorg/lowcoder-ce-node-service:latest
    container_name: lowcoder-node-service
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "6060:6060"
    environment:
      PUID: "9001"
      PGID: "9001"
      LOWCODER_API_SERVICE_URL: "http://lowcoder-api-service:8080"
    restart: unless-stopped
    depends_on:
      - lowcoder-api-service

  ##
  ## Start Lowcoder web frontend
  ##
  lowcoder-frontend:
    image: lowcoderorg/lowcoder-ce-frontend:latest
    container_name: lowcoder-frontend
    ports:
      - "3000:3000"
    environment:
      PUID: "9001"
      PGID: "9001"
      LOWCODER_MAX_REQUEST_SIZE: 20m
      LOWCODER_MAX_QUERY_TIMEOUT: 120
      LOWCODER_API_SERVICE_URL: "http://lowcoder-api-service:8080"
      LOWCODER_NODE_SERVICE_URL: "http://lowcoder-node-service:6060"
    restart: unless-stopped
    depends_on:
      - lowcoder-node-service
      - lowcoder-api-service

