name: Build Docker Image

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
#  REGISTRY: ${{ secrets.REGISTRY_AI }}
  REGISTRY: registry.cn-wulanchabu.aliyuncs.com
  IMAGE_NAME: cloudladder_shangyun/cloudladder-fe

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_AI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AI_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Get short SHA
        id: short-sha
        run: echo "::set-output name=short_sha::$(echo ${GITHUB_SHA::9})"

      - name: Build and push FE Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          build-args: REACT_APP_COMMIT_ID=${{ steps.short-sha.outputs.short_sha }}
          push: true
          file: ./Dockerfile
          tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ steps.short-sha.outputs.short_sha }},${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest
          labels: ${{ steps.meta.outputs.labels }}
          target: lowcoder-frontend
          platform: linux/amd64,linux/arm64,linux/arm/v7
